
service: bonjour-example

provider:
  name: aws
  runtime: python3.8
  stage: 'dev'
  region: 'us-east-2'
  role: arn:aws:iam::555989344246:role/bonjour-example-role




functions:
  hello:
    handler: lambdas/greeting/handler.hello

plugins:
  - serverless-python-requirements
